### ISSUE TITLE
importing python scripts

### ISSUE THREAD

**Issue by yangyushi** [royallgroup/TCC#116]
In the [python wrapper documentation](https://royallgroup.github.io/TCC/html/python_scripts.html#example-wrapper-script), the code contains the follow import:

```
from tcc import wrapper
from file_readers import xyz
```

This will need two folders, `TCC` and `TCC/tcc_python_scripts`, being added to the `PYTHONPATH`, so that user can use both `tcc_python_scripts` and `tcc` inside the `tcc_python_scripts `. This can be counter intuitive.

Importing all the sub-packages inside `TCC/tcc_python_scripts` in the file `TCC/tcc_python_scripts/__init__.py` may be a way to make it better. Since users will be required to add only the `TCC` to the `PYTHONPATH`.

**Comment by merrygoat** [comment]
Thank you Yushi. I have been struggling to get this to work well and that is a very good idea. I will try that.

**Comment by merrygoat** [comment]
@yangyushi @tranqui I found some motivation to work on this at last!

It turns out that setuptools is an excellent way to deal with distribution of packages. I have implemented setuptools for the python scripts, tweaked a couple of the Python scripts a bit and updated the documentation. 

It would be good if you could just have a go using the Python wrapper to see if that is better. The changes are in the setuptools branch. Note that the online documentation hasn't yet updated as it reads from the master branch, You will have to look at the documentation direct from the docs folder. To install the python scripts is just "pip install ." from the root folder.

All of the tests that use the wrapper have been broken. I will fix them tomorrow and also move the integration tests across to using the wrapper as well.

**Comment by yangyushi** [comment]
@merrygoat `pip install .` works for me!
