### ISSUE TITLE
Python Wrapper: Box Size

### ISSUE THREAD

**Issue by bc1032** [royallgroup/TCC#89]
It would be helpful if the box size in the Python Wrapper was automatically calculated without any further work needing doing to it.

**Comment by tranqui** [comment]
This is a bug: the issue is that the snapshot class in the wrapper stores boxes as [[x_left, x_right], [y_left, y_right], [z_left, z_right]] format if that information is available, whereas the TCCWrapper uses the more practical [x_right - x_left, y_right - y_left, z_right - z_left] format. I will fix this so that the TCCWrapper parses the first type into the second if it is not already in the right format.
